xRssReader/Models/FeedItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace xRssReader.Models
{
	public class FeedItem
	{
		//Title
		//Link
		//Description
		//PubDate

		private readonly string title;

		private readonly string link;

		private readonly string description;

		private readonly string pubDate;

		public string Title => title;

		public string Link => link;

		public string Description => description;

		public string PubDate => pubDate;


		public FeedItem(string title, string link, string description, string pubDate)
		{
			this.title = title;
			this.link = link;
			this.description = description;
			this.pubDate = pubDate;
		}
	}
}

xRssReader/ViewModels/FeedItemCollection.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using xRssReader.Models;

namespace xRssReader.ViewModels
{
	public class FeedItemCollection
	{
		private readonly string defaultRssUrl;

		private readonly IList<FeedItem> feedItems;

		public string DefaultRssUrl => defaultRssUrl;

		public IList<FeedItem> FeedItems => feedItems;

		public FeedItemCollection(string defaultRSSUrl, IList<FeedItem> feedItems)
		{
			this.defaultRssUrl = defaultRSSUrl;
			this.feedItems = feedItems;
		}
	}
}

xRssReader/Controllers/FeedController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.ServiceModel.Syndication;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using xRssReader.Models;
using xRssReader.ViewModels;

namespace xRssReader.Controllers
{
	public class FeedController : Controller
	{
		private const string ColumnHeaderTitleIdentifier = "title";

		private const string ColumnHeaderPubDateIdentifier = "pubdate";

		private const string AscendingSortOrderIdentifier = "asc";

		private const string DescendingSortOrderIdentifier = "desc";

		private readonly string defaultRssUrl;

		public FeedController()
		{
			defaultRssUrl = ConfigurationManager.AppSettings["DefaultRssUrl"];
		}

		[HttpGet]
		public ActionResult Index()
		{
			FeedItemCollection viewModel = null;
			IList<FeedItem> feedItems = GetFeed(defaultRssUrl);

			if (feedItems != null && feedItems.Count > 0)
			{
				viewModel = new FeedItemCollection(defaultRssUrl, feedItems);
			}

			ViewBag.TitleSortOrder = AscendingSortOrderIdentifier;
			ViewBag.PubDateSortOrder = AscendingSortOrderIdentifier;

			return View(viewModel);
		}

		[HttpPost]
		public ActionResult Index(string theRssUrl)
		{
			string rssUrl;
			IList<FeedItem> feedItems = null;
			FeedItemCollection viewModel = null;

			if (String.IsNullOrEmpty(theRssUrl))
			{
				rssUrl = defaultRssUrl;
			}
			else
			{
				rssUrl = theRssUrl;
			}

			feedItems = GetFeed(rssUrl);
			viewModel = new FeedItemCollection(rssUrl, feedItems);

			ViewBag.TitleSortOrder = AscendingSortOrderIdentifier;
			ViewBag.PubDateSortOrder = AscendingSortOrderIdentifier;

			return View(viewModel);
		}

		public ActionResult GetItemsSorted(string rssUrl, string sortByField, string sortOrder)
		{
			IList<FeedItem> feedItems = GetFeed(rssUrl);
			FeedItemCollection viewModel = new FeedItemCollection(rssUrl, feedItems);

			if (feedItems != null && feedItems.Count > 0)
			{
				feedItems = SortFeed(sortByField, sortOrder, feedItems);
				viewModel = new FeedItemCollection(rssUrl, feedItems);

				if (sortByField == ColumnHeaderTitleIdentifier)
				{
					if (sortOrder == AscendingSortOrderIdentifier)
					{
						ViewBag.TitleSortOrder = DescendingSortOrderIdentifier;
					}
					else
					{
						ViewBag.TitleSortOrder = AscendingSortOrderIdentifier;
					}
				}
				else if (sortByField == ColumnHeaderPubDateIdentifier)
				{
					if (sortOrder == AscendingSortOrderIdentifier)
					{
						ViewBag.PubDateSortOrder = DescendingSortOrderIdentifier;
					}
					else
					{
						ViewBag.PubDateSortOrder = AscendingSortOrderIdentifier;
					}
				}
			}

			return PartialView("_FeedItems", viewModel);
		}

		private IList<FeedItem> SortFeed(string sortByField, string sortOrder, IList<FeedItem> feedItems)
		{
			if (!String.IsNullOrEmpty(sortByField) && !String.IsNullOrEmpty(sortOrder))
			{
				if (sortByField == ColumnHeaderTitleIdentifier)
				{
					if (sortOrder == AscendingSortOrderIdentifier)
					{
						feedItems = feedItems.OrderBy(item => item.Title).ToList();
					}
					else
					{
						feedItems = feedItems.OrderByDescending(item => item.Title).ToList();
					}
				}
				else if (sortByField == ColumnHeaderPubDateIdentifier)
				{
					if (sortOrder == AscendingSortOrderIdentifier)
					{
						feedItems = feedItems.OrderBy(item => item.PubDate).ToList();
					}
					else
					{
						feedItems = feedItems.OrderByDescending(item => item.PubDate).ToList();
					}
				}
			}

			return feedItems;
		}

		private IList<FeedItem> GetFeed(string url)
		{
			IList<FeedItem> feedItems = null;

			using (XmlReader reader = XmlReader.Create(url))
			{
				SyndicationFeed feed = SyndicationFeed.Load(reader);
				feedItems = feed.Items.Select(
					item => new FeedItem(
						item.Title.Text,
						item.Links.First().Uri.ToString(),
						item.Summary.Text,
						item.PublishDate.DateTime.ToString())).ToList();

			}

			return feedItems;
		}
	}
}

xRssReader/Views/Feed/Index.cshtml
@model xRssReader.ViewModels.FeedItemCollection
@{
    ViewBag.Title = "RSS feed reader page";
}

<br />

@using (Html.BeginForm())
{
    <input type="URL" name="theRssUrl" placeholder="Please type RSS feed url here..." class="form-control" value="@Model.DefaultRssUrl" style="min-width:100%" />
    <br />
    <input type="submit" class="btn btn-danger" />
}

<br />

@if (Model != null)
{
    <div id="feedItems">
        @{ Html.RenderPartial("_FeedItems", Model); }
        @*<table class="table table-hover">
            <thead>
                <tr>
                    <th><a href="javascript:sort('title', '@ViewBag.TitleSortOrder');">Title</a></th>
                    <th><a href="javascript:sort('pubdate', '@ViewBag.PubDateSortOrder');">Publish Date</a></th>
                </tr>
            </thead>
            <tbody>
                @if (Model.FeedItems != null && Model.FeedItems.Count > 0)
                {
                    foreach (var item in Model.FeedItems)
                    {
                        <tr>
                            <td><a href="@item.Link" target="_blank">@item.Title</a></td>
                            <td>@item.PubDate</td>
                        </tr>
                    }
                }
            </tbody>
        </table>*@
    </div>
}
<script>
    function sort(field, order) {
        $.post(
            "/Feed/GetItemsSorted",
            {
                rssUrl: $("input[name='theRssUrl']").val(),
                sortByField: field,
                sortOrder: order
            },
            function (result) {
                $("#feedItems").html(result);
                //console.log(data);
            }
        );
    }
</script>

xRssReader/Views/Feed/_FeedItems.cshtml
@model xRssReader.ViewModels.FeedItemCollection
<table class="table table-hover">
    <thead>
        <tr>
            <th><a href="javascript:sort('title', '@ViewBag.TitleSortOrder');">Title</a></th>
            <th><a href="javascript:sort('pubdate', '@ViewBag.PubDateSortOrder');">Publish Date</a></th>
        </tr>
    </thead>
    <tbody>
        @if (Model.FeedItems != null && Model.FeedItems.Count > 0)
        {
            foreach (var item in Model.FeedItems)
            {
                <tr>
                    <td><a href="@item.Link" target="_blank">@item.Title</a></td>
                    <td>@item.PubDate</td>
                </tr>
            }
        }
    </tbody>
</table>

xRssReader/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("xRssReader", "Index", "Feed", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - xRssReader Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>